@tool
extends Resource
class_name ItemCatalogue



## WARNING:
## A autogenerated, inspectable snapshot of the item database.
## This file is overwritten automatically when the game is run in the editor. Do not edit manually.

## All registered items, keyed by their StringName ID.
@export var items_by_id: Dictionary = {}

## All registered capabilities. The top-level key is the script's file path (String).
## The value is another Dictionary where keys are item IDs and values are the capability resources.
@export var capabilities_by_script_path: Dictionary = {}

@export var capabilities_by_name:Dictionary = {}
